### ISSUE TITLE
推荐网页：高等院校三千所

### ISSUE THREAD

**Issue by DiamonWoo** [LeslieLeung/cat-fish-weekly#1]
投稿类型：网站
链接：https://Laosheng.top/fuwu/yuanxiao
推荐原因：为填报志愿的考生和家长们助力！

[高等院校三千所](https://Laosheng.top/fuwu/yuanxiao) 收录了全国的高校名单和网址。里面有一个**中国高校层级图谱**，然后按照这个层级，列出了全国高校名单，并且都加上了院校的网址，点进去就能看到官方主页。

《高校所》常年更新，最初是为了帮助考生填报志愿，后来发现，各大学网站里面资源丰富，是一个很大的宝库，我会逐步添加各校的特色网页。

![Snap11-2024版高校层级图谱+广东高校165所](https://github.com/LeslieLeung/cat-fish-weekly/assets/62480272/cf816068-406c-403b-9d2b-fcd93f0eff37)

**Comment by LeslieLeung** [comment]
很有意思的网站！预定下期收录。

ps. 感觉排版有点乱，视觉上不够友好。

**Comment by LeslieLeung** [comment]
已在 [vol. 030](https://ameow.xyz/archives/weekly-030) 发布。

**Comment by DiamonWoo** [comment]
> 已在 [vol. 030](https://ameow.xyz/archives/weekly-030) 发布。

看到了，[猫鱼周刊 vol. 030](https://ameow.xyz/archives/weekly-030) 国内的「开源」环境

谢谢收录，最近还在忙着修订。

> 很有意思的网站！预定下期收录。
> ps. 感觉排版有点乱，视觉上不够友好。

这是难点，链接密度太大了！版式设计是集成网页能否阅读舒适的难点，我还一直在摸索。相对而言，《[千县网](https://Laosheng.top/fuwu/qianxian)》那个页面就整齐很多。因为那个层级比较少，省市县三级，而《高校所》层级更多，标记更多。希望以后能找到更好的版式。
